name: "CD (Entrega/Delivery Continua): Main Workflow"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy        
        run: |
          git config --global url.ssh://git@github.com:robwilstocco/Origins.git
          npm install
          npm run deploy
