name: "CD (Entrega/Delivery Continua): Main Workflow"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        env:
          MY_EMAIL: robwilstocco@gmail.com
          MY_NAME: robertwilson
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          npm install
          npm run deploy
