name: "CD (Entrega/Delivery Continua): Main Workflow"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest 
    environment:
      name: prod
      url: https://robwilstocco.github.io/Origins
    steps:
      - uses: actions/checkout@v3
      - name: Run Deploy
        run: |
          npm install
          npm run deploy
