name: "CD (Entrega/Delivery Continua): Main Workflow"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://robwilstocco.github.io/Origins/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Deploy
        run: |
          git remote -v
          git config user.name
          npm install
          npm run deploy
