name: "CD (Entrega/Delivery Continua): Main Workflow"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3      
      - name: Run Deploy
        run: |
          # npm install
          npm run deploy
